"""Deterministic offline MockLLM used as a safe fallback.

Produces structured, plausible responses for SAP Note validation,
analysis and orchestration prompts so the app remains fully usable
without any external service.
"""
from __future__ import annotations

import re
import time
from typing import Any, Iterable

from .base import LLMResponse


_NOTE_RE = re.compile(r"\b(\d{6,10})\b")


class MockLLM:
    provider_name = "mock"
    supports_streaming = True

    def __init__(self, reason: str = "MockLLM fallback") -> None:
        self.reason = reason

    # ------------------------------------------------------------------
    def _detect_notes(self, prompt: str) -> list[str]:
        return list(dict.fromkeys(_NOTE_RE.findall(prompt or "")))

    def _detect_system(self, prompt: str) -> str:
        p = (prompt or "").upper()
        if "S/4" in p or "S4HANA" in p or "MDS_LOAD_COCKPIT" in p:
            return "S4HANA"
        if "ECC" in p or "CVI_COCKPIT" in p:
            return "ECC"
        return "UNKNOWN"

    def _build_text(self, prompt: str, system: str | None) -> str:
        notes = self._detect_notes(prompt)
        sys_kind = self._detect_system(prompt or "")
        notes_txt = ", ".join(notes) if notes else "(none detected)"

        sections = [
            "## Executive Summary",
            f"Detected SAP Notes: {notes_txt}",
            f"Target system class: {sys_kind}",
            "",
            "## Validation",
            "- Note existence: OK (mock)",
            "- Component applicability: OK (mock)",
            "- Release applicability: OK (mock)",
            "- Already implemented: false",
            "- Obsolete: false",
            "- Prerequisite notes: none required (mock)",
            "- Conflicting notes: none (mock)",
            "- Transport availability: OK (mock)",
            "- User authorization: OK (mock)",
            "",
            "## AI Analysis",
            "- Business impact: Master data synchronization stability improvement",
            "- Technical impact: CVI/MDS framework corrections",
            "- Dependencies: none blocking",
            "- Recommended sequence: linear",
            "- Predicted conflicts: none",
            "",
            "## Implementation Plan",
            "1. Open SNOTE session",
            "2. Download listed notes",
            "3. Implement prerequisites first (none required)",
            "4. Implement target notes in sequence",
            "5. Auto-create transport request",
            "6. Capture logs, request approval before release",
            "",
            "## Post-Implementation Checks",
        ]
        if sys_kind == "S4HANA":
            sections += [
                "Run MDS_LOAD_COCKPIT:",
                "- Initial Load readiness: OK",
                "- Replication readiness: OK",
                "- BP sync: OK",
                "- Data consistency: OK",
                "- Pending loads: 0",
            ]
        else:
            sections += [
                "Run CVI_COCKPIT:",
                "- BP synchronization: OK",
                "- Customer synchronization: OK",
                "- Vendor synchronization: OK",
                "- Data consistency: OK",
                "- Mapping validation: OK",
            ]

        sections += [
            "",
            "## Risks and Mitigation",
            "- Risk: partial implementation → Mitigation: rollback of transport",
            "- Risk: lock entries → Mitigation: retry with SM12 pre-check",
            "",
            "## Notes",
            f"(Generated by MockLLM — reason: {self.reason})",
        ]
        return "\n".join(sections)

    # ------------------------------------------------------------------
    def complete(
        self,
        prompt: str,
        *,
        system: str | None = None,
        temperature: float | None = None,
        max_tokens: int | None = None,
    ) -> LLMResponse:
        t0 = time.time()
        text = self._build_text(prompt, system)
        return LLMResponse(
            text=text,
            provider=self.provider_name,
            model="mock-1",
            latency_ms=int((time.time() - t0) * 1000),
            raw={"reason": self.reason},
        )

    def stream(
        self,
        prompt: str,
        *,
        system: str | None = None,
        temperature: float | None = None,
        max_tokens: int | None = None,
    ) -> Iterable[str]:
        text = self._build_text(prompt, system)
        # Emit in ~40-char chunks so the UI can render a live stream.
        for i in range(0, len(text), 40):
            yield text[i : i + 40]

    def health(self) -> dict[str, Any]:
        return {
            "provider": self.provider_name,
            "status": "ok",
            "reason": self.reason,
            "supports_streaming": self.supports_streaming,
        }